### ISSUE TITLE
Metrics Not Displayed on Dashboards Due to Missing k8s-infra Chart Values in Latest Helm Chart

### ISSUE THREAD

**Issue by ishu-harsh** [SigNoz/charts#559]
Summary:
In the latest version of the signoz Helm chart, the k8s-infra chart values are not included, leading to metrics not being displayed in the dashboards. This is impacting the observability of Kubernetes infrastructure metrics.

Expected Behavior:
Kubernetes infrastructure metrics (e.g., node metrics, pod metrics) should be displayed in the dashboards by default.

Actual Behavior:
Metrics related to Kubernetes infrastructure are missing from the dashboards.

Root Cause:
The latest version of the signoz Helm chart does not include default values for the k8s-infra chart, which is necessary for collecting Kubernetes infrastructure metrics.

Suggested Fix:
Include the default values for the k8s-infra chart in the signoz Helm chart's values.yaml file.
Alternatively, provide clear documentation for users to manually enable and configure k8s-infra in their custom values.

**Comment by grandwizard28** [comment]
Hi @ishu-harsh,
With the merge of https://github.com/SigNoz/charts/pull/477 and from SigNoz chart version 0.48.0 onwards (https://github.com/SigNoz/charts/pull/479/files), k8s-infra is no longer a subchart of SigNoz. 

It needs to be installed separately.

**Comment by mgilham** [comment]
A note for anyone else running into this: I had to define `otelCollectorEndpoint` for the `k8s-infra` Helm chart, since it's no longer being pulled in via dependency.

To match [the example Helm deployment in the docs](https://signoz.io/docs/install/kubernetes/others/), this looks like adding `--set otelCollectorEndpoint='my-release-otel-collector:4317'`.

**Comment by ishu-harsh** [comment]
@grandwizard28 Thanks you.

@mgilham Wanted to know is there any specific reason you guys remove the k8-infra agent from chart?

**Comment by grandwizard28** [comment]
@ishu-harsh,
This change is part of our effort to improve the helm-chart architecture by following the separation of concerns principle. Both charts solve separate concerns. One is for installing SigNoz and the other is for collecting and sending telemetry to SigNoz.

**Comment by joshualyon** [comment]
Just a heads up that it looks like the [website documentation for the SigNoz Kubernetes (self-hosted) install](https://signoz.io/docs/install/kubernetes/others/) still indicates that k8s-infra is bundled:

> The [SigNoz Helm chart](https://signoz.io/docs/install/kubernetes/) will install the following components into your Kubernetes cluster:
> 
> * Query Service (backend service)
> * Web UI (frontend)
> * OpenTelemetry Collectors
> * Alertmanager
> * ClickHouse chart (datastore)
> * **K8s-Infra chart (k8s infra metrics/logs collectors)**

That documentation probably needs to be updated to reflect that you need to [manually install signoz/k8s-infra](https://signoz.io/docs/tutorial/kubernetes-infra-metrics/) rather than indicating that it's automatically installed.

**Comment by dbgarf-flatfile** [comment]
@grandwizard28 I'd like to suggest a bundled helm chart as an available option. a great many self-hosted users of this system want and expect k8s-infra chart to be installed. maybe that doesn't need to be a default for everyone, but between the out-of-date documentation and the additional manual steps, this is meeting your users' needs very well.

**Comment by grandwizard28** [comment]
Hey @dbgarf-flatfile,
Thanks for the heads up! We have updated the documentation as well and created a dedicated issue for better visibility https://github.com/SigNoz/charts/issues/633
